import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import createIgnore from "ignore";

import { resolvePackagedAppArtifacts } from "../scripts/lib/packaged-app.mjs";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

test("packaged verification authority is the selected app bundle", () => {
  const appPath = path.join(repoRoot, "dist", "Example.app");
  const artifacts = resolvePackagedAppArtifacts(appPath);
  assert.equal(artifacts.appPath, appPath);
  assert.equal(artifacts.asarPath, path.join(appPath, "Contents", "Resources", "app.asar"));
  assert.equal(artifacts.unpackedPath, `${artifacts.asarPath}.unpacked`);
  assert.notEqual(artifacts.asarPath, path.join(repoRoot, ".build", "app.asar"));
  assert.throws(() => resolvePackagedAppArtifacts(path.join(repoRoot, ".build", "app.asar")), /\.app bundle/);
});

test("publication ignore rules retain reconstructed frontend source", async () => {
  const ignoreRules = await readFile(path.join(repoRoot, ".gitignore"), "utf8");
  assert.match(ignoreRules, /^\/recovered\/$/m);
  assert.doesNotMatch(ignoreRules, /^recovered\/$/m);
  const retained = "frontend/src/recovered/ui/sand-form-primitives.css";
  const matcher = createIgnore().add(ignoreRules);
  assert.equal(matcher.ignores(retained), false, `${retained} must remain addable in a fresh repository`);
  assert.equal(matcher.ignores("recovered/generated-output.txt"), true, "root recovery output must remain ignored");
});

test("default packaging keeps the polished checksum-pinned renderer", async () => {
  const source = await readFile(path.join(repoRoot, "scripts", "package-macos.mjs"), "utf8");
  assert.match(source, /import \{ buildFidelityReconstructedAsar \} from "\.\/clean-build\.mjs"/);
  assert.match(source, /await buildFidelityReconstructedAsar\(\)/);
});

test("reconstructed packaging badges the Dock icon before codesign", async () => {
  const source = await readFile(path.join(repoRoot, "scripts", "package-macos.mjs"), "utf8");
  assert.match(source, /import \{ applyReconstructedDockIcon \} from "\.\/lib\/reconstructed-dock-icon\.mjs"/);
  assert.match(source, /await applyReconstructedDockIcon\(outputApp\)/);
  const iconIndex = source.indexOf("await applyReconstructedDockIcon(outputApp)");
  const signIndex = source.indexOf("signAppBundleAdHoc(outputApp)");
  assert.ok(iconIndex >= 0 && signIndex > iconIndex, "Dock icon badge must run before ad-hoc signing");
});

test("Router settings use the trusted backend and display recorded inference usage", async () => {
  const rendererPatch = await readFile(path.join(repoRoot, "scripts", "lib", "router-renderer-patch.mjs"), "utf8");
  const preload = await readFile(path.join(repoRoot, "source", "electron-preload", "preload.ts"), "utf8");
  const mainEdge = await readFile(path.join(repoRoot, "source", "electron-main", "main-edge.ts"), "utf8");
  const inference = await readFile(path.join(repoRoot, "source", "host", "extensions", "inference", "inference-service.ts"), "utf8");
  const cursorSession = await readFile(path.join(repoRoot, "source", "host", "extensions", "inference", "cursor-session.ts"), "utf8");
  const cursorBackend = await readFile(path.join(repoRoot, "source", "shared", "node", "cursor-backend", "cursor-inference.ts"), "utf8");
  const providers = await readFile(path.join(repoRoot, "source", "host", "extensions", "inference", "provider-session.ts"), "utf8");
  const codexDirect = await readFile(path.join(repoRoot, "source", "host", "extensions", "inference", "codex-direct-responses.ts"), "utf8");
  const turnShell = await readFile(path.join(repoRoot, "source", "host", "runner", "turn-run-shell.ts"), "utf8");
  const coordinator = await readFile(path.join(repoRoot, "source", "node-agent-coordinator", "inference-router.ts"), "utf8");
  const coordinatorMain = await readFile(path.join(repoRoot, "source", "node-agent-coordinator", "main.ts"), "utf8");
  const mcpBridge = await readFile(path.join(repoRoot, "source", "node-agent-coordinator", "routed-mcp-bridge.ts"), "utf8");
  const localDocker = await readFile(path.join(repoRoot, "source", "electron-main", "box", "local-docker-host-connector.ts"), "utf8");
  const secretsIpc = await readFile(path.join(repoRoot, "source", "electron-main", "adapters", "ipc.ts"), "utf8");
  const remoteHooks = await readFile(path.join(repoRoot, "source", "packages", "agent", "tools", "core", "remote-hooks.ts"), "utf8");
  const settingsStore = await readFile(path.join(repoRoot, "source", "shared", "node", "settings", "sand-settings-store.ts"), "utf8");
  const mainRpc = await readFile(path.join(repoRoot, "source", "shared", "rpc", "main.ts"), "utf8");
  const coordinatorRpc = await readFile(path.join(repoRoot, "source", "shared", "rpc", "coordinator.ts"), "utf8");
  const gatewayProtocol = await readFile(path.join(repoRoot, "source", "host", "gateway-protocol.ts"), "utf8");
  const runnerComposition = await readFile(path.join(repoRoot, "source", "host", "host-runner-composition.ts"), "utf8");
  const electronMain = await readFile(path.join(repoRoot, "source", "electron-main", "main.ts"), "utf8");
  const coordinatorProvider = await readFile(path.join(repoRoot, "source", "electron-main", "coordinator", "production-provider.ts"), "utf8");
  const coordinatorInspect = await readFile(path.join(repoRoot, "source", "electron-main", "coordinator", "coordinator-inspect.ts"), "utf8");
  const coordinatorResync = await readFile(path.join(repoRoot, "source", "electron-main", "coordinator", "coordinator-resync.ts"), "utf8");
  const hostBox = await readFile(path.join(repoRoot, "source", "host", "extensions", "forever-box", "host-box.ts"), "utf8");
  const composer = await readFile(path.join(repoRoot, "frontend", "src", "recovered", "features", "conversation", "workspace", "composer.tsx"), "utf8");
  const viewCss = await readFile(path.join(repoRoot, "frontend", "src", "recovered", "features", "conversation", "workspace", "view.css"), "utf8");
  const pluginsBrowser = await readFile(path.join(repoRoot, "frontend", "src", "recovered", "features", "plugins", "overlay", "browser.tsx"), "utf8");
  const webShim = await readFile(path.join(repoRoot, "source", "server-main", "web-shim.js"), "utf8");
  assert.match(rendererPatch, /desktop\.agent\.getInferenceRouter\(\)/);
  assert.match(rendererPatch, /desktop\.agent\.setInferenceRouter\("openrouter"\)/);
  assert.match(rendererPatch, /desktop\.agent\.setInferenceRouter\(s\.provider,\{model:r\}\)/);
  assert.match(rendererPatch, /desktop\.agent\.setInferenceRouter\(s\.provider,\{computerModel:r\}\)/);
  assert.match(rendererPatch, /desktop\.agent\.setInferenceRouter\(s\.provider,\{summarizeModel:r\}\)/);
  assert.match(rendererPatch, /desktop\.agent\.setInferenceRouter\(s\.provider,\{reasoningEffort:r\}\)/);
  assert.match(rendererPatch, /desktop\.agent\.setInferenceRouter\(s\.provider,\{computerReasoningEffort:r\}\)/);
  assert.match(rendererPatch, /function RRouterEffort/);
  assert.match(rendererPatch, /Think reasoning/);
  assert.match(rendererPatch, /Drive reasoning/);
  assert.match(rendererPatch, /RRouterEffortOptions/);
  assert.match(rendererPatch, /settings-openrouter-reasoning-effort/);
  assert.match(rendererPatch, /desktop\.agent\.listOpenRouterModels\(\)/);
  assert.match(rendererPatch, /function RRouterOpenRouterModels/);
  assert.match(rendererPatch, /Search models/);
  assert.match(rendererPatch, /RRouterModelId/);
  assert.match(rendererPatch, /RRouterModelMatches/);
  assert.match(rendererPatch, /Recommended · /);
  assert.match(rendererPatch, /x-ai\/grok-4\.6/);
  assert.match(rendererPatch, /Think model/);
  assert.match(rendererPatch, /Drive model/);
  assert.match(rendererPatch, /Summarize model/);
  assert.match(rendererPatch, /Same as Think/);
  assert.match(rendererPatch, /function RRouterPresets/);
  assert.match(rendererPatch, /children:"High"/);
  assert.match(rendererPatch, /children:"Med"/);
  assert.match(rendererPatch, /children:"Low"/);
  assert.match(rendererPatch, /__inherit__/);
  assert.match(rendererPatch, /function RIsDocker/);
  assert.match(rendererPatch, /getDesktopEnvironment/);
  assert.match(rendererPatch, /runtime==="docker"/);
  assert.match(rendererPatch, /function RLocalProfile/);
  assert.match(rendererPatch, /function RLocalProfile\(\)\{const z=H\.c\(/);
  assert.match(rendererPatch, /function RInputValue/);
  assert.match(rendererPatch, /draftName:RInputValue\(i\)/);
  assert.match(rendererPatch, /gravatar\.com\/avatar/);
  assert.match(rendererPatch, /desktop\.agent\.getLocalProfile/);
  assert.match(rendererPatch, /desktop\.agent\.setLocalProfile/);
  assert.match(rendererPatch, /Save profile/);
  assert.match(rendererPatch, /Save updates the sidebar name and avatar in this app/);
  assert.doesNotMatch(rendererPatch, /sidebar name and avatar on this Mac/);
  assert.match(rendererPatch, /COMPOSIO_API_KEY/);
  assert.match(rendererPatch, /costUsd/);
  assert.match(rendererPatch, /desktop\.agent\.getBoxRuntime\(\)/);
  assert.doesNotMatch(rendererPatch, /desktop\.agent\.setBoxRuntime/);
  assert.doesNotMatch(rendererPatch, /role:"switch"/);
  assert.doesNotMatch(rendererPatch, /Use local Docker VM/);
  assert.match(rendererPatch, /function REdgeError/);
  assert.match(rendererPatch, /local Docker VM on this Mac/);
  assert.match(localDocker, /resolveDockerCliPath/);
  assert.match(localDocker, /dockerSpawnEnvironment/);
  assert.match(localDocker, /formatDockerUnavailable/);
  assert.match(rendererPatch, /onValueChange:u=>\{if\(u!==null\)void t\(u\)\}/);
  assert.match(rendererPatch, /desktop\.secrets\.upsert/);
  assert.match(rendererPatch, /synced===false/);
  assert.match(rendererPatch, /computer did not receive it/);
  assert.doesNotMatch(rendererPatch, /settings\.router-provider\.v1/);
  assert.match(rendererPatch, /Usage for OpenRouter/);
  assert.match(rendererPatch, /Spend/);
  assert.match(rendererPatch, /Requests/);
  assert.match(rendererPatch, /Input tokens/);
  assert.match(rendererPatch, /Last used/);
  assert.match(rendererPatch, /Tracked activity/);
  assert.match(preload, /getLocalProfile: \(\) => edge\("getLocalProfile"\)/);
  assert.match(preload, /setLocalProfile: \(profile: \{ readonly name\?: string; readonly email\?: string \}\) => edge\("updateLocalProfile", profile\)/);
  assert.match(preload, /setInferenceRouter: \(provider: string, extras\?: \{ readonly model\?: string; readonly computerModel\?: string \| null; readonly summarizeModel\?: string \| null; readonly reasoningEffort\?: string; readonly computerReasoningEffort\?: string \}\)/);
  assert.match(preload, /computerModel: extras\.computerModel/);
  assert.match(preload, /summarizeModel: extras\.summarizeModel/);
  assert.match(preload, /reasoningEffort: extras\.reasoningEffort\.trim\(\)/);
  assert.match(preload, /computerReasoningEffort: extras\.computerReasoningEffort\.trim\(\)/);
  assert.match(preload, /listOpenRouterModels: \(\) => edge\("listOpenRouterModels"\)/);
  assert.match(mainRpc, /listOpenRouterModels: \{ args: "none" \}/);
  assert.match(preload, /getBoxRuntime: \(\) => edge\("getBoxRuntime"\)/);
  assert.match(preload, /setBoxRuntime: \(mode: string\) => edge\("setBoxRuntime", \{ mode \}\)/);
  assert.match(mainEdge, /openRouterComputerModel: storedOpenRouterComputerModel\(deps\)/);
  assert.match(mainEdge, /invoke\(deps\.settingsStore, "setInferenceProvider", provider\)/);
  assert.match(mainEdge, /invoke\(deps\.settingsStore, "setOpenRouterModel", requested\)/);
  assert.match(mainEdge, /setOpenRouterComputerModel/);
  assert.match(mainEdge, /setOpenRouterReasoningEffort/);
  assert.match(mainEdge, /setOpenRouterComputerReasoningEffort/);
  assert.match(mainEdge, /reasoningEffort: storedOpenRouterReasoningEffort\(deps\)/);
  assert.match(mainEdge, /computerReasoningEffort: storedOpenRouterComputerReasoningEffort\(deps\)/);
  assert.match(mainEdge, /listOpenRouterModels:/);
  assert.match(mainEdge, /fetchOpenRouterCatalog/);
  assert.match(mainEdge, /currentId: \[model, computerModel, summarizeModel\]/);
  assert.match(mainEdge, /setOpenRouterSummarizeModel/);
  assert.match(mainEdge, /summarizeModel: storedOpenRouterSummarizeModel\(deps\)/);
  assert.match(mainEdge, /invoke\(deps\.boxRecovery, "restartCoordinator"\)/);
  assert.match(mainEdge, /mode === "local-docker"\) await startLocalDockerBox\(settingsPath\); else await stopLocalDockerBox\(\)/);
  assert.match(mainEdge, /const previous = invoke\(deps\.settingsStore, "getBoxRuntime"\)/);
  assert.match(mainEdge, /if \(isSandBoxRuntime\(previous\)\) invoke\(deps\.settingsStore, "setBoxRuntime", previous\)/);
  assert.match(localDocker, /public\.ecr\.aws\/k0i0n2g5\/cursorenvironments\/universal:sand-box-latest/);
  assert.match(localDocker, /"127\.0\.0\.1:1340:1340"/);
  assert.match(localDocker, /SAND_DATA_ROOT=\/home\/box\/sand-data/);
  assert.match(localDocker, /LOCAL_DOCKER_SCHEMA_VERSION = "7"/);
  assert.match(localDocker, /installLocalDockerBoxSecrets/);
  assert.match(localDocker, /installLocalDockerChromeConverge/);
  assert.match(localDocker, /--disable-gpu --disable-software-rasterizer/);
  assert.match(localDocker, /sand-chrome-keep/);
  assert.match(localDocker, /RESTART_CHROME/);
  assert.match(localDocker, /timeout 60 bash \/tmp\/sand-chrome-converge\.sh/);
  assert.match(localDocker, /sand-data\/chrome-profiles/);
  assert.match(localDocker, /setsid \/usr\/local\/bin\/sand-chrome-keep.*&/);
  assert.match(localDocker, /hostBoxSecretsPath/);
  assert.match(localDocker, /\/home\/box\/sand-data\/box-secrets\.json/);
  assert.match(localDocker, /\["cp", target,/);
  assert.match(secretsIpc, /afterSecretsMutation/);
  assert.match(secretsIpc, /writeLocalDockerBoxSecrets/);
  assert.match(localDocker, /dst=\/home\/box\/sand-host\/host-main\.cjs,readonly/);
  assert.match(localDocker, /connect: async \(\) => await localConnect\(\)/);
  assert.match(inference, /recordInferenceUsage\(provider/);
  assert.match(inference, /routerSettings\.getInferenceProvider\(\)/);
  assert.match(inference, /typeof extendedUsage\.then === "function"/);
  assert.match(inference, /createProviderPromptSession\(provider, sessionOptions\)/);
  assert.match(inference, /createProviderPromptSession\(provider, \{ \.\.\.\(sessionOptions \?\? \{\}\), isSummarizationSession: true \}\)/);
  assert.match(providers, /https:\/\/chatgpt\.com\/backend-api\/codex/);
  assert.match(providers, /headers\.set\("ChatGPT-Account-Id", credentials\.accountId\)/);
  assert.match(providers, /streamCodexDirectResponses/);
  assert.doesNotMatch(providers, /provider\.responses\(configuredCodexModel\(\)\)/);
  assert.match(codexDirect, /store: false/);
  assert.match(codexDirect, /response\.output_text\.delta/);
  assert.match(codexDirect, /type: "function_call_output"/);
  assert.match(providers, /parameters: jsonSchema\(parameters\)/);
  assert.match(providers, /You are Grok Bot, a warm, concise desktop assistant/);
  assert.match(providers, /Do not announce screenshots, clicks, or waits\. Speak only when you are blocked or done\./);
  assert.match(providers, /maxRetries: 0/);
  assert.match(providers, /Do not close the box browser/);
  assert.match(providers, /You do have a screen you can drive/);
  assert.match(providers, /experimental_toToolResultContent/);
  assert.match(providers, /openRouterToolResultContent/);
  assert.match(codexDirect, /codexFunctionCallOutput/);
  assert.match(coordinatorResync, /inference_router/);
  assert.match(coordinatorResync, /getInferenceRouterSettings/);
  assert.match(coordinatorProvider, /getInferenceRouterSettings/);
  assert.match(hostBox, /preferredBoxVncUrl/);
  assert.match(electronMain, /reconstructedDevToolsAllowed/);
  assert.match(coordinatorProvider, /coordinatorInspectForkOptions/);
  assert.match(coordinatorInspect, /GROK_BOT_INSPECT_COORDINATOR/);
  assert.match(coordinator, /appendRoutedInferenceLog/);
  assert.match(coordinator, /onProgress/);
  assert.match(coordinator, /step-finish/);
  assert.match(coordinator, /coalesceRoutedProviderMessages/);
  assert.match(coordinator, /settleStep/);
  assert.match(coordinator, /discard-narration/);
  assert.match(coordinator, /turn-retry/);
  assert.match(coordinator, /isRoutedTransientProviderError/);
  assert.match(coordinator, /routedSettledAssistantContent/);
  assert.match(coordinator, /screenshot-loop/);
  assert.match(coordinator, /listRoutedComputerTools/);
  assert.match(coordinator, /turnNeedsRoutedComputer\(prompt, chromeAlreadyOpen\)/);
  assert.match(coordinator, /const slot = drive \? "drive" as const : "think" as const/);
  assert.match(coordinator, /executeRoutedComputerTool/);
  assert.match(coordinator, /isRoutedComputerTool\(definition\) \? "executeRoutedComputerTool" : "executeRoutedMcpTool"/);
  assert.match(coordinator, /ROUTED_COMPUTER_INFERENCE_TURN_TIMEOUT_MS/);
  assert.match(coordinatorRpc, /listRoutedComputerTools/);
  assert.match(gatewayProtocol, /listRoutedComputerTools/);
  assert.match(runnerComposition, /productionParentSubagentConfigs/);
  assert.match(runnerComposition, /isBrowserUseSubagentEnabled: \(\) => method\(experiments, "isBrowserUseSubagentEnabled"\)/);
  assert.match(providers, /mcpServers: \{ grok_bot_plugins:/);
  assert.match(providers, /recordRoutedUsage\(provider, usage\)/);
  assert.match(providers, /queryClaude/);
  assert.match(providers, /tools: \[\]/);
  assert.match(providers, /allowedTools: \["mcp__grok_bot_plugins__\*"\]/);
  assert.match(providers, /https:\/\/openrouter\.ai\/api\/v1/);
  assert.match(providers, /OpenRouter needs OPENROUTER_API_KEY/);
  assert.match(providers, /configuredOpenRouterModel\(\)/);
  assert.match(providers, /configuredOpenRouterComputerModel\(\)/);
  assert.match(providers, /configuredOpenRouterSummarizeModel\(\)/);
  assert.match(providers, /configuredOpenRouterSlotModel\(slot\)/);
  assert.match(providers, /configuredOpenRouterReasoningEffort\(slot\)/);
  assert.match(providers, /runPiDriveSession/);
  assert.match(providers, /slot === "drive"/);
  assert.match(providers, /injectOpenRouterReasoningIntoBody/);
  assert.match(providers, /boundOpenRouterRequestBody/);
  assert.match(providers, /openRouterFetch/);
  assert.match(providers, /openRouterSlotFromSession\(sessionOptions\)/);
  assert.doesNotMatch(providers, /routedToolsIncludeComputer\(definitions \?\? \[\]\)/);
  assert.match(providers, /abortSignal/);
  assert.match(providers, /awaitAbortRace/);
  assert.doesNotMatch(providers, /openai\/gpt-5\.2/);
  assert.match(settingsStore, /getOpenRouterModel/);
  assert.match(settingsStore, /SAND_DROP_QWEN_COMPUTER_MODEL_MIGRATION_ID/);
  assert.match(settingsStore, /getOpenRouterComputerModel/);
  assert.match(settingsStore, /getOpenRouterSummarizeModel/);
  assert.match(settingsStore, /getOpenRouterReasoningEffort/);
  assert.match(settingsStore, /getOpenRouterComputerReasoningEffort/);
  assert.match(settingsStore, /DEFAULT_OPENROUTER_MODEL/);
  assert.match(settingsStore, /DEFAULT_OPENROUTER_REASONING_EFFORT/);
  assert.match(settingsStore, /DEFAULT_OPENROUTER_COMPUTER_REASONING_EFFORT/);
  assert.match(remoteHooks, /sanitizeToolInputForStruct/);
  assert.match(remoteHooks, /from "\.\.\/\.\.\/\.\.\/\.\.\/shared\/struct-json\.js"/);
  assert.match(providers, /SAND_BOX_DATA_ROOT, BOX_SECRETS_FILENAME/);
  assert.match(providers, /local-docker-credential/);
  assert.match(providers, /\.grokbot"/);
  assert.match(providers, /\.cursor", "sand-dev"/);
  assert.match(cursorSession, /routedProvider !== "cursor"/);
  assert.match(cursorSession, /createProviderPromptSession\(routedProvider, sessionOptions\)/);
  assert.match(cursorBackend, /routedProvider !== "cursor"/);
  assert.match(cursorBackend, /createProviderPromptSession\(routedProvider\)/);
  assert.doesNotMatch(rendererPatch, /ANTHROPIC_API_KEY|OPENAI_API_KEY/);
  assert.match(turnShell, /inferenceProvider === "cursor"/);
  assert.match(turnShell, /createProviderPromptSession\(inferenceProvider, sessionOptions\)/);
  assert.match(turnShell, /createProviderPromptSession\(inferenceProvider, \{ isSummarizationSession: true \}\)/);
  assert.match(coordinator, /method !== "sendPrompt" \|\| provider === "cursor"/);
  assert.match(coordinator, /executeTool: async \(definition, toolArgs, toolCallId\)/);
  assert.match(coordinatorMain, /command\(commands, "listRoutedMcpTools", args\)/);
  assert.match(coordinator, /inference-router-transcript\.json/);
  assert.match(mcpBridge, /openWorldHint: !readOnly/);
  assert.match(coordinator, /schemaVersion: 2/);
  assert.match(coordinator, /\["getAgentTranscriptTail", "openAgentTail", "getAgentTranscriptWindow"\]/);
  assert.match(coordinator, /\.map\(projectInferenceRouterTranscriptEntry\)/);
  assert.match(coordinator, /readonly richText\?: string/);
  assert.match(coordinator, /richText: entry\.richText/);
  assert.match(coordinator, /awaitRoutedRetryBackoff\(options\.composingDelayMs \?\? 1_200, turnAbort\)/);
  assert.match(coordinator, /method === "stopRoutedTurn"/);
  assert.match(coordinator, /method === "deleteAgent" \|\| method === "deleteAgents"/);
  assert.match(coordinator, /await dropAgents\(ids\)/);
  assert.match(coordinator, /abortAgentTurn\(agentId, "supersede"\)/);
  assert.match(coordinator, /stampLiveTurnState/);
  assert.match(coordinator, /controller\.signal\.aborted/);
  assert.match(coordinatorRpc, /stopRoutedTurn/);
  assert.match(composer, /aria-label="Stop"/);
  assert.match(composer, /onStop\?\(\): void \| Promise<void>/);
  assert.match(webShim, /method: "stopRoutedTurn"/);
  assert.match(webShim, /grok-bot-composer-stop/);
  assert.match(webShim, /nativeComposerStop/);
  assert.match(webShim, /background:#fff/);
  assert.match(webShim, /background:#171914/);
  assert.match(webShim, /coordinator restarted; reconnecting/);
  assert.match(providers, /grokRouterSystemPrompt\(pluginTools\)/);
  assert.match(providers, /No Connect plugins are attached/);
  assert.match(composer, /sand-prompt-stop-glyph/);
  assert.match(viewCss, /cursor-text-primary/);
  assert.match(pluginsBrowser, /No tools loaded for this connector/);
  assert.match(gatewayProtocol, /listInstalledMcpServers/);
  assert.match(gatewayProtocol, /listMcpServerTools/);
  assert.match(webShim, /sand:vnc-viewer-visible/);
  assert.match(webShim, /refreshNoVncIframe/);
  assert.match(webShim, /IntersectionObserver/);
  assert.doesNotMatch(webShim, /#e5484d/);
  assert.match(coordinator, /method === "reactToMessage"/);
  assert.match(coordinator, /reaction\.by === "me"/);
  assert.match(coordinator, /currentActivity: surface\.activity/);
  assert.match(coordinator, /kind: "tool"/);
  assert.match(coordinator, /ROUTED_INFERENCE_TURN_TIMEOUT_MS/);
  assert.match(coordinator, /AbortSignal\.timeout\(timeoutMs\)/);
  assert.match(coordinator, /abortSignal/);
  assert.match(coordinator, /streaming/);
  assert.match(coordinator, /postEvent\("agents"/);
  assert.match(coordinator, /createRoutedMcpBridge/);
  assert.match(coordinator, /listRoutedMcpTools/);
  assert.match(coordinator, /executeRoutedMcpTool/);
  assert.match(mcpBridge, /server\.listen\(0, "127\.0\.0\.1"/);
  assert.match(mcpBridge, /readOnlyHint: readOnly/);
  assert.match(mcpBridge, /request\.url !== `\/mcp\/\$\{secret\}`/);
  assert.match(coordinator, /kind: "send-message"/);
  assert.match(coordinatorMain, /createCoordinatorInferenceRouter/);
  assert.match(coordinatorMain, /routed\.handled/);
});
